---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: default
  name: k8s-auth
spec:
  # point to name of VaultConnection CR
  vaultConnectionRef: vault-on-kind
  # Same as `vault auth enable -path k8s kubernetes`
  method: kubernetes
  mount: k8s
  # Same as `vault read auth/k8s/role/readonly`
  kubernetes:
    role: readonly
    # k8s SA using to fetch secrets from Vault
    serviceAccount: default
