---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret-app
  namespace: default
spec:
  vaultAuthRef: k8s-auth
  # same as `vault secrets enable -path kv2 kv-v2`
  type: kv-v2
  mount: kv2
  # same as `vault read kv2/app-secret`
  path: app-secret
  refreshAfter: 60s
  destination:
    create: true
    name: db-password
