---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  # provide namespace where app will refer vault's secrets
  namespace: default
  name: vault-on-kind
spec:
  address: http://vault-server.vault.svc.cluster.local:8200
