Vagrant.configure("2") do |config|
  # Docker provider
  config.vm.define "app" do |app|
    app.vm.provider "docker" do |d|
      d.name = "web"
      d.image = "bitnami/nginx:latest"
      d.ports = ["8080:8080", "8443:8443"]
    end
  end

  config.vm.define "db" do |app|
    app.vm.provider "docker" do |d|
      d.name = "db"
      d.image = "bitnami/mysql"
      d.env = {"MYSQL_ROOT_PASSWORD": ENV['MYSQL_ROOT_PASSWORD']}
      d.ports = ["3306:3306"]
    end
  end

  # vmware_desktop provider
  config.vm.define "alpine" do |machine|
    # Fetch box file from local
    machine.vm.box_url = "file://base.box"
    machine.vm.provider "vmware_desktop" do |fusion|
      fusion.gui = true
      fusion.allowlist_verified = true
      fusion.linked_clone = false
      fusion.enable_vmrun_ip_lookup = false
    end
    machine.vm.hostname = "hwakabh-alpine"
    machine.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "debian" do |machine|
    # Fetch from HCP Vagrant Registry
    machine.vm.box = "bento/debian-11"
    machine.vm.box_version = "202407.22.0"
    machine.vm.box_architecture = "arm64" # for Appli Silicon

    machine.vm.provider "vmware_desktop" do |fusion|
      fusion.gui = true
      fusion.allowlist_verified = true
      fusion.vmx["ethernet0.virtualdev"] = "vmxnet3"
      fusion.linked_clone = false
      fusion.enable_vmrun_ip_lookup = false
    end

    machine.vm.hostname = "hwakabh-debian-11"
    machine.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
