# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # provider/docker usecase with multi machine
  config.vm.define "app" do |app|
    app.vm.provider "docker" do |d|
      d.name = "web"
      d.image = "bitnami/nginx:latest"
      d.ports = ["8080:8080", "8443:8443"]
    end
  end

  config.vm.define "db" do |app|
    app.vm.provider "docker" do |d|
      d.name = "db"
      d.image = "bitnami/mysql"
      d.env = {"MYSQL_ROOT_PASSWORD": 'password'}
      d.ports = ["3306:3306"]
    end
  end

  # provisioner/docker usecase
  config.vm.define "debian" do |node|
    # https://portal.cloud.hashicorp.com/vagrant/discover/bento/debian-11
    node.vm.box = "bento/debian-11"
    node.vm.provider "vmware_desktop" do |fusion|
      fusion.gui = false
      fusion.allowlist_verified = true
      fusion.linked_clone = false
      fusion.enable_vmrun_ip_lookup = false
    end
    node.vm.provision "nssetup",
      type: "shell",
      inline: "echo 'nameserver 8.8.8.8' >> /etc/resolv.conf"
    node.vm.provision "setup", type: "docker" do |docker|
      docker.images = [
        "alpine:latest"
      ]
      docker.build_image "/vagrant",
        args: "-t nginx-web:local"
      docker.run "web-server",
        image: "nginx-web:local",
        args: "-p 80:80",
        daemonize: true
      docker.run "linux-daemon",
        image: "alpine:latest",
        cmd: "sleep 30"
      docker.run "linux-oneoff",
        image: "alpine:latest",
        daemonize: true,
        cmd: "sleep 15",
        restart: "no"
    end
  end

end
